export default {
  SET_USERNAME: "SET_USERNAME",
  SET_TIMEFORMAT: "SET_TIMEFORMAT",
  SET_THEME: "SET_THEME",
  TOGGLE_CTRL_ENTER: "TOGGLE_CTRL_ENTER",
  RESET_DEFAULTS: "RESET_DEFAULTS",

  SET_MESSAGES: "SET_MESSAGES"
};
